version: '3.8'

services:
  data-api:
    build:
      context: /api/.
      dockerfile: Dockerfile
    container_name: data-api
    ports:
      - "555:555"
    volumes:
      - ./api:/api
  sqlite:
    image: nouchka/sqlite3
    container_name: sqlite
    hostname: sqlite
    volumes:
      - ./sqlite:/sqlite
    stdin_open: true
    tty: true
    command: sh
      
  python-app:
    build:
      context: /app/.
      dockerfile: Dockerfile
    container_name: python-app
    depends_on:
      - sqlite
      - data-api
    ports:
      - "666:666"
    volumes:
      - ./sqlite:/sqlite